chains:
  constants:
    default_transpose: 0x0
    empty_phrase: 0xff
  count: 0x80
  fields:
    phrase:
      default: 0xff
      offset: 0x0
    transpose:
      offset: 0x1
  offset: 0x9a5e
  step_count: 0x10
  step_size: 0x2
effect_settings:
  offset: 0x1a5c1
eq:
  offset: 0x1ad5e
fx:
  block_count: 0x3
  block_size: 0x2
  constants:
    default_value: 0x0
    empty_key: 0xff
  fields:
    key:
      default: 0xff
      offset: 0x0
      enums:
        # Instrument-specific FX enums (including common ones for each type)
        '0x00':  # WAVSYNTH
          - m8.enums.wavsynth.M8WavSynthFX
          - m8.enums.M8SequencerFX
          - m8.enums.M8MixerFX
          - m8.enums.M8ModulatorFX
        '0x01':  # MACROSYNTH
          - m8.enums.macrosynth.M8MacroSynthFX
          - m8.enums.M8SequencerFX
          - m8.enums.M8MixerFX
          - m8.enums.M8ModulatorFX
        '0x02':  # SAMPLER
          - m8.enums.sampler.M8SamplerFX
          - m8.enums.M8SequencerFX
          - m8.enums.M8MixerFX
          - m8.enums.M8ModulatorFX
        '0x04':  # FMSYNTH
          - m8.enums.fmsynth.M8FMSynthFX
          - m8.enums.M8SequencerFX
          - m8.enums.M8MixerFX
          - m8.enums.M8ModulatorFX
    value:
      offset: 0x1
groove:
  offset: 0xee
instruments:
  block_size: 0xd7
  common_fields:
    finetune:
      default: 0x80
      offset: 0x11
    name:
      default: ' '
      offset: 0x1
      size: 0xc
      type: STRING
    name_length:
      offset: 0xc
    pitch:
      offset: 0x10
    table_tick:
      default: 0x1
      offset: 0xe
    transpose_eq:
      components:
        eq:
          default: 0x1
          nibble: 0x2
        transpose:
          default: 0x4
          nibble: 0x1
      offset: 0xd
      type: UINT4_2
    type:
      offset: 0x0
    volume:
      offset: 0xf
  count: 0x80
  modulators_offset: 0x3f
  offset: 0x13a3e
  param_types:
    STRING: 0x2
    UINT8: 0x1
  type_id_map:
    0: WAVSYNTH
    1: MACROSYNTH
    2: SAMPLER
    4: FMSYNTH
  types:
    FMSYNTH:
      params:
        algo:
          enums:
          - m8.enums.fmsynth.M8FMSynthAlgos
          offset: 0x12
        shape1:
          enums:
          - m8.enums.fmsynth.M8FMSynthShapes
          offset: 0x13
        shape2:
          enums:
          - m8.enums.fmsynth.M8FMSynthShapes
          offset: 0x14
        shape3:
          enums:
          - m8.enums.fmsynth.M8FMSynthShapes
          offset: 0x15
        shape4:
          enums:
          - m8.enums.fmsynth.M8FMSynthShapes
          offset: 0x16
        ratio1:
          offset: 0x17
        ratio_fine1:
          offset: 0x18
        ratio2:
          offset: 0x19
        ratio_fine2:
          offset: 0x1a
        ratio3:
          offset: 0x1b
        ratio_fine3:
          offset: 0x1c
        ratio4:
          offset: 0x1d
        ratio_fine4:
          offset: 0x1e
        level1:
          offset: 0x1f
        feedback1:
          offset: 0x20
        level2:
          offset: 0x21
        feedback2:
          offset: 0x22
        level3:
          offset: 0x23
        feedback3:
          offset: 0x24
        level4:
          offset: 0x25
        feedback4:
          offset: 0x26
        mod_a1:
          offset: 0x27
        mod_b1:
          offset: 0x28
        mod_a2:
          offset: 0x29
        mod_b2:
          offset: 0x2a
        mod_a3:
          offset: 0x2b
        mod_b3:
          offset: 0x2c
        mod_a4:
          offset: 0x2d
        mod_b4:
          offset: 0x2e
        mod_1:
          offset: 0x2f
        mod_2:
          offset: 0x30
        mod_3:
          offset: 0x31
        mod_4:
          offset: 0x32
        amp:
          offset: 0x33
        chorus:
          offset: 0x37
        cutoff:
          default: 0xff
          offset: 0x31
        delay:
          offset: 0x38
        dry:
          default: 0xc0
          offset: 0x36
        filter:
          offset: 0x30
        limit:
          offset: 0x34
        pan:
          default: 0x80
          offset: 0x35
        res:
          offset: 0x32
        reverb:
          offset: 0x39
      type_id: 0x4
    MACROSYNTH:
      params:
        amp:
          offset: 0x1a
        chorus:
          offset: 0x1e
        color:
          default: 0x80
          offset: 0x14
        cutoff:
          default: 0xff
          offset: 0x18
        degrade:
          offset: 0x15
        delay:
          offset: 0x1f
        dry:
          default: 0xc0
          offset: 0x1d
        filter:
          enums:
          - m8.enums.M8FilterTypes
          offset: 0x17
        limit:
          enums:
          - m8.enums.M8LimitTypes
          offset: 0x1b
        pan:
          default: 0x80
          offset: 0x1c
        redux:
          offset: 0x16
        res:
          offset: 0x19
        reverb:
          offset: 0x20
        shape:
          enums:
          - m8.enums.macrosynth.M8MacroSynthShapes
          offset: 0x12
        timbre:
          default: 0x80
          offset: 0x13
      type_id: 0x1
    SAMPLER:
      params:
        amp:
          offset: 0x1b
        chorus:
          offset: 0x1f
        cutoff:
          default: 0xff
          offset: 0x19
        degrade:
          offset: 0x17
        delay:
          offset: 0x20
        dry:
          default: 0xc0
          offset: 0x1e
        filter:
          enums:
          - m8.enums.M8FilterTypes
          offset: 0x18
        length:
          default: 0xff
          offset: 0x16
        limit:
          enums:
          - m8.enums.M8LimitTypes
          offset: 0x1c
        loop_start:
          offset: 0x15
        pan:
          default: 0x80
          offset: 0x1d
        play_mode:
          enums:
          - m8.enums.sampler.M8SamplerPlayMode
          offset: 0x12
        res:
          offset: 0x1a
        reverb:
          offset: 0x21
        slice:
          offset: 0x13
        start:
          offset: 0x14
      sample_path:
        default: ''
        offset: 0x57
        size: 0x80
        type: STRING
      type_id: 0x2
    WAVSYNTH:
      params:
        amp:
          offset: 0x1a
        chorus:
          offset: 0x1e
        cutoff:
          default: 0xff
          offset: 0x18
        delay:
          offset: 0x1f
        dry:
          default: 0xc0
          offset: 0x1d
        filter:
          enums:
          - m8.enums.M8FilterTypes
          offset: 0x17
        limit:
          enums:
          - m8.enums.M8LimitTypes
          offset: 0x1b
        mult:
          default: 0x80
          offset: 0x14
        pan:
          default: 0x80
          offset: 0x1c
        res:
          offset: 0x19
        reverb:
          offset: 0x20
        scan:
          offset: 0x16
        shape:
          enums:
          - m8.enums.wavsynth.M8WavSynthShapes
          offset: 0x12
        size:
          default: 0x80
          offset: 0x13
        warp:
          offset: 0x15
      type_id: 0x0
metadata:
  block_size: 0x93
  fields:
    directory:
      default: /Songs/
      offset: 0x0
      size: 0x80
      type: STRING
    key:
      offset: 0x92
    name:
      default: HELLO
      offset: 0x86
      size: 0xc
      type: STRING
    quantize:
      offset: 0x85
    tempo:
      default: 120.0
      offset: 0x81
      size: 0x4
      type: FLOAT
    transpose:
      offset: 0x80
  offset: 0xe
midi_mapping:
  offset: 0x1a5fe
modulators:
  block_size: 0x6
  constants:
    default_amount: 0xff
    empty_destination: 0x0
  count: 0x4
  default_config:
  - 0x0
  - 0x0
  - 0x3
  - 0x3
  fields:
    amount:
      default: 0xff
      offset: 0x1
    type_dest_byte:
      offset: 0x0
  type_id_map:
    0: m8.api.modulators.M8AHDEnvelope
    1: m8.api.modulators.M8ADSREnvelope
    2: m8.api.modulators.M8DrumEnvelope
    3: m8.api.modulators.M8LFO
    4: m8.api.modulators.M8TriggerEnvelope
    5: m8.api.modulators.M8TrackingEnvelope
  types:
    ADSR_ENVELOPE:
      fields:
        amount:
          default: 0xff
          offset: 0x1
        attack:
          offset: 0x2
        decay:
          default: 0x80
          offset: 0x3
        destination:
          enums:
            '0x00':
            - m8.enums.wavsynth.M8WavSynthModDestinations
            '0x01':
            - m8.enums.macrosynth.M8MacroSynthModDestinations
            '0x02':
            - m8.enums.sampler.M8SamplerModDestinations
            '0x04':
            - m8.enums.fmsynth.M8FMSynthModDestinations
          nibble: 0x1
          offset: 0x0
        release:
          default: 0x80
          offset: 0x5
        sustain:
          default: 0x80
          offset: 0x4
      id: 0x1
    AHD_ENVELOPE:
      fields:
        amount:
          default: 0xff
          offset: 0x1
        attack:
          offset: 0x2
        decay:
          default: 0x80
          offset: 0x4
        destination:
          enums:
            '0x00':
            - m8.enums.wavsynth.M8WavSynthModDestinations
            '0x01':
            - m8.enums.macrosynth.M8MacroSynthModDestinations
            '0x02':
            - m8.enums.sampler.M8SamplerModDestinations
            '0x04':
            - m8.enums.fmsynth.M8FMSynthModDestinations
          nibble: 0x1
          offset: 0x0
        hold:
          offset: 0x3
      id: 0x0
    DRUM_ENVELOPE:
      fields:
        amount:
          default: 0xff
          offset: 0x1
        body:
          default: 0x10
          offset: 0x3
        decay:
          default: 0x80
          offset: 0x4
        destination:
          enums:
            '0x00':
            - m8.enums.wavsynth.M8WavSynthModDestinations
            '0x01':
            - m8.enums.macrosynth.M8MacroSynthModDestinations
            '0x02':
            - m8.enums.sampler.M8SamplerModDestinations
            '0x04':
            - m8.enums.fmsynth.M8FMSynthModDestinations
          nibble: 0x1
          offset: 0x0
        peak:
          offset: 0x2
      id: 0x2
    LFO:
      fields:
        amount:
          default: 0xff
          offset: 0x1
        destination:
          enums:
            '0x00':
            - m8.enums.wavsynth.M8WavSynthModDestinations
            '0x01':
            - m8.enums.macrosynth.M8MacroSynthModDestinations
            '0x02':
            - m8.enums.sampler.M8SamplerModDestinations
            '0x04':
            - m8.enums.fmsynth.M8FMSynthModDestinations
          nibble: 0x1
          offset: 0x0
        frequency:
          default: 0x10
          offset: 0x4
        oscillator:
          offset: 0x2
        trigger:
          offset: 0x3
      id: 0x3
    TRACKING_ENVELOPE:
      fields:
        amount:
          default: 0xff
          offset: 0x1
        destination:
          enums:
            '0x00':
            - m8.enums.wavsynth.M8WavSynthModDestinations
            '0x01':
            - m8.enums.macrosynth.M8MacroSynthModDestinations
            '0x02':
            - m8.enums.sampler.M8SamplerModDestinations
            '0x04':
            - m8.enums.fmsynth.M8FMSynthModDestinations
          nibble: 0x1
          offset: 0x0
        high_value:
          default: 0x7f
          offset: 0x4
        low_value:
          offset: 0x3
        source:
          offset: 0x2
      id: 0x5
    TRIGGER_ENVELOPE:
      fields:
        amount:
          default: 0xff
          offset: 0x1
        attack:
          offset: 0x2
        decay:
          default: 0x40
          offset: 0x4
        destination:
          enums:
            '0x00':
            - m8.enums.wavsynth.M8WavSynthModDestinations
            '0x01':
            - m8.enums.macrosynth.M8MacroSynthModDestinations
            '0x02':
            - m8.enums.sampler.M8SamplerModDestinations
            '0x04':
            - m8.enums.fmsynth.M8FMSynthModDestinations
          nibble: 0x1
          offset: 0x0
        hold:
          offset: 0x3
        source:
          offset: 0x5
      id: 0x4
phrases:
  constants:
    base_data_size: 0x3
    empty_instrument: 0xff
    empty_note: 0xff
    empty_velocity: 0xff
  count: 0xff
  fields:
    fx:
      offset: 0x3
      size: 0x6
    instrument:
      default: 0xff
      offset: 0x2
    note:
      default: 0xff
      offset: 0x0
      enums:
        - m8.enums.M8Notes
    velocity:
      default: 0xff
      offset: 0x1
  offset: 0xaee
  step_count: 0x10
  step_size: 0x9
scale:
  offset: 0x1aa7e
song:
  col_count: 0x8
  constants:
    empty_chain: 0xff
  offset: 0x2ee
  row_count: 0xff
table:
  offset: 0xba3e
version:
  offset: 0xa