chains:
  constants:
    default_transpose: 0
    empty_phrase: 255
  count: 128
  fields:
    phrase:
      default: 255
      offset: 0
    transpose:
      offset: 1
  offset: 39518
  step_count: 16
  step_size: 2
effect_settings:
  offset: 107969
eq:
  offset: 109918
fx:
  block_count: 3
  block_size: 2
  constants:
    default_value: 0
    empty_key: 255
  fields:
    key:
      default: 255
      offset: 0
    value:
      offset: 1
groove:
  offset: 238
instruments:
  MACROSYNTH:
    params:
      amp:
        offset: 26
      chorus:
        offset: 30
      color:
        default: 128
        offset: 20
      cutoff:
        default: 255
        offset: 24
      degrade:
        offset: 21
      delay:
        offset: 31
      dry:
        default: 192
        offset: 29
      filter:
        enums:
        - m8.enums.M8FilterTypes
        offset: 23
      limit:
        enums:
        - m8.enums.M8LimitTypes
        offset: 27
      pan:
        default: 128
        offset: 28
      redux:
        offset: 22
      res:
        offset: 25
      reverb:
        offset: 32
      shape:
        enums:
        - m8.enums.macrosynth.M8MacroSynthShapes
        offset: 18
      timbre:
        default: 128
        offset: 19
    type_id: 1
  SAMPLER:
    params:
      amp:
        offset: 27
      chorus:
        offset: 31
      cutoff:
        default: 255
        offset: 25
      degrade:
        offset: 23
      delay:
        offset: 32
      dry:
        default: 192
        offset: 30
      filter:
        enums:
        - m8.enums.M8FilterTypes
        offset: 24
      length:
        default: 255
        offset: 22
      limit:
        enums:
        - m8.enums.M8LimitTypes
        offset: 28
      loop_start:
        offset: 21
      pan:
        default: 128
        offset: 29
      play_mode:
        enums:
        - m8.enums.sampler.M8SamplerPlayMode
        offset: 18
      res:
        offset: 26
      reverb:
        offset: 33
      slice:
        offset: 19
      start:
        offset: 20
    sample_path:
      default: ''
      offset: 87
      size: 128
      type: STRING
    type_id: 2
  WAVSYNTH:
    params:
      amp:
        offset: 26
      chorus:
        offset: 30
      cutoff:
        default: 255
        offset: 24
      delay:
        offset: 31
      dry:
        default: 192
        offset: 29
      filter:
        enums:
        - m8.enums.M8FilterTypes
        offset: 23
      limit:
        enums:
        - m8.enums.M8LimitTypes
        offset: 27
      mult:
        default: 128
        offset: 20
      pan:
        default: 128
        offset: 28
      res:
        offset: 25
      reverb:
        offset: 32
      scan:
        offset: 22
      shape:
        enums:
        - m8.enums.wavsynth.M8WavSynthShapes
        offset: 18
      size:
        default: 128
        offset: 19
      warp:
        offset: 21
    type_id: 0
  block_size: 215
  common_fields:
    finetune:
      default: 128
      offset: 17
    name:
      default: ' '
      offset: 1
      size: 12
      type: STRING
    name_length:
      offset: 12
    pitch:
      offset: 16
    table_tick:
      default: 1
      offset: 14
    transpose_eq:
      offset: 13
      type: "UINT4_2"
      components:
        transpose:
          nibble: 1
          default: 4
        eq:
          nibble: 2
          default: 1
    type:
      offset: 0
    volume:
      offset: 15
  count: 128
  modulators_offset: 63
  offset: 80446
  param_types:
    STRING: 2
    UINT8: 1
metadata:
  block_size: 147
  fields:
    directory:
      default: /Songs/
      offset: 0
      size: 128
      type: STRING
    key:
      offset: 146
    name:
      default: HELLO
      offset: 134
      size: 12
      type: STRING
    quantize:
      offset: 133
    tempo:
      default: 120.0
      offset: 129
      size: 4
      type: FLOAT
    transpose:
      offset: 128
  offset: 14
midi_mapping:
  offset: 108030
modulators:
  block_size: 6
  constants:
    default_amount: 255
    empty_destination: 0
  count: 4
  default_config:
  - 0
  - 0
  - 3
  - 3
  fields:
    amount:
      default: 255
      offset: 1
    type_dest_byte:
      offset: 0
  type_id_map:
    0: m8.api.modulators.M8AHDEnvelope
    1: m8.api.modulators.M8ADSREnvelope
    2: m8.api.modulators.M8DrumEnvelope
    3: m8.api.modulators.M8LFO
    4: m8.api.modulators.M8TriggerEnvelope
    5: m8.api.modulators.M8TrackingEnvelope
  types:
    ADSR_ENVELOPE:
      fields:
        amount:
          default: 255
          offset: 1
        attack:
          offset: 2
        decay:
          default: 128
          offset: 3
        destination:
          enums:
            '0x00':
            - m8.enums.wavsynth.M8WavSynthModDestinations
            '0x01':
            - m8.enums.macrosynth.M8MacroSynthModDestinations
            '0x02':
            - m8.enums.sampler.M8SamplerModDestinations
          nibble: 1
          offset: 0
        release:
          default: 128
          offset: 5
        sustain:
          default: 128
          offset: 4
      id: 1
    AHD_ENVELOPE:
      fields:
        amount:
          default: 255
          offset: 1
        attack:
          offset: 2
        decay:
          default: 128
          offset: 4
        destination:
          enums:
            '0x00':
            - m8.enums.wavsynth.M8WavSynthModDestinations
            '0x01':
            - m8.enums.macrosynth.M8MacroSynthModDestinations
            '0x02':
            - m8.enums.sampler.M8SamplerModDestinations
          nibble: 1
          offset: 0
        hold:
          offset: 3
      id: 0
    DRUM_ENVELOPE:
      fields:
        amount:
          default: 255
          offset: 1
        body:
          default: 16
          offset: 3
        decay:
          default: 128
          offset: 4
        destination:
          enums:
            '0x00':
            - m8.enums.wavsynth.M8WavSynthModDestinations
            '0x01':
            - m8.enums.macrosynth.M8MacroSynthModDestinations
            '0x02':
            - m8.enums.sampler.M8SamplerModDestinations
          nibble: 1
          offset: 0
        peak:
          offset: 2
      id: 2
    LFO:
      fields:
        amount:
          default: 255
          offset: 1
        destination:
          enums:
            '0x00':
            - m8.enums.wavsynth.M8WavSynthModDestinations
            '0x01':
            - m8.enums.macrosynth.M8MacroSynthModDestinations
            '0x02':
            - m8.enums.sampler.M8SamplerModDestinations
          nibble: 1
          offset: 0
        frequency:
          default: 16
          offset: 4
        oscillator:
          offset: 2
        trigger:
          offset: 3
      id: 3
    TRACKING_ENVELOPE:
      fields:
        amount:
          default: 255
          offset: 1
        destination:
          enums:
            '0x00':
            - m8.enums.wavsynth.M8WavSynthModDestinations
            '0x01':
            - m8.enums.macrosynth.M8MacroSynthModDestinations
            '0x02':
            - m8.enums.sampler.M8SamplerModDestinations
          nibble: 1
          offset: 0
        high_value:
          default: 127
          offset: 4
        low_value:
          offset: 3
        source:
          offset: 2
      id: 5
    TRIGGER_ENVELOPE:
      fields:
        amount:
          default: 255
          offset: 1
        attack:
          offset: 2
        decay:
          default: 64
          offset: 4
        destination:
          enums:
            '0x00':
            - m8.enums.wavsynth.M8WavSynthModDestinations
            '0x01':
            - m8.enums.macrosynth.M8MacroSynthModDestinations
            '0x02':
            - m8.enums.sampler.M8SamplerModDestinations
          nibble: 1
          offset: 0
        hold:
          offset: 3
        source:
          offset: 5
      id: 4
phrases:
  constants:
    base_data_size: 3
    empty_instrument: 255
    empty_note: 255
    empty_velocity: 255
  count: 255
  fields:
    fx:
      offset: 3
      size: 6
    instrument:
      default: 255
      offset: 2
    note:
      default: 255
      offset: 0
    velocity:
      default: 255
      offset: 1
  offset: 2798
  step_count: 16
  step_size: 9
scale:
  offset: 109182
song:
  col_count: 8
  constants:
    empty_chain: 255
  offset: 750
  row_count: 255
table:
  offset: 47678
version:
  offset: 10
