chains:
  constants:
    default_transpose: 0
    empty_phrase: 255
  count: 128
  fields:
    phrase:
      default: 255
      offset: 0
    transpose:
      offset: 1
  offset: 39518
  step_count: 16
  step_size: 2
effect_settings:
  offset: 107969
eq:
  offset: 109918
fx:
  block_count: 3
  block_size: 2
  constants:
    default_value: 0
    empty_key: 255
  fields:
    key:
      default: 255
      enums:
        '0x00':
        - m8.enums.wavsynth.M8WavSynthFX
        - m8.enums.M8SequencerFX
        - m8.enums.M8MixerFX
        - m8.enums.M8ModulatorFX
        '0x01':
        - m8.enums.macrosynth.M8MacroSynthFX
        - m8.enums.M8SequencerFX
        - m8.enums.M8MixerFX
        - m8.enums.M8ModulatorFX
        '0x02':
        - m8.enums.sampler.M8SamplerFX
        - m8.enums.M8SequencerFX
        - m8.enums.M8MixerFX
        - m8.enums.M8ModulatorFX
        '0x04':
        - m8.enums.fmsynth.M8FMSynthFX
        - m8.enums.M8SequencerFX
        - m8.enums.M8MixerFX
        - m8.enums.M8ModulatorFX
      offset: 0
    value:
      offset: 1
groove:
  offset: 238
instruments:
  block_size: 215
  common_fields:
    finetune:
      default: 128
      offset: 17
    name:
      default: ' '
      offset: 1
      size: 12
      type: STRING
    name_length:
      offset: 12
    pitch:
      offset: 16
    table_tick:
      default: 1
      offset: 14
    transpose_eq:
      components:
        eq:
          default: 1
          nibble: 2
        transpose:
          default: 4
          nibble: 1
      offset: 13
      type: UINT4_2
    type:
      offset: 0
    volume:
      offset: 15
  count: 128
  modulators_offset: 63
  offset: 80446
  param_types:
    STRING: 2
    UINT8: 1
  types:
    FMSYNTH:
      params:
        algo:
          enums:
          - m8.enums.fmsynth.M8FMSynthAlgos
          offset: 18
        amp:
          offset: 54
        chorus:
          offset: 58
        cutoff:
          default: 255
          offset: 52
        delay:
          offset: 59
        dry:
          default: 192
          offset: 57
        feedback1:
          offset: 32
        feedback2:
          offset: 34
        feedback3:
          offset: 36
        feedback4:
          offset: 38
        filter:
          enums:
          - m8.enums.M8FilterTypes
          offset: 51
        level1:
          offset: 31
        level2:
          offset: 33
        level3:
          offset: 35
        level4:
          offset: 37
        limit:
          enums:
          - m8.enums.M8LimitTypes
          offset: 55
        mod_1:
          offset: 47
        mod_2:
          offset: 48
        mod_3:
          offset: 49
        mod_4:
          offset: 50
        mod_a1:
          enums:
          - m8.enums.fmsynth.M8FMSynthModABValues
          offset: 39
        mod_a2:
          enums:
          - m8.enums.fmsynth.M8FMSynthModABValues
          offset: 40
        mod_a3:
          enums:
          - m8.enums.fmsynth.M8FMSynthModABValues
          offset: 41
        mod_a4:
          enums:
          - m8.enums.fmsynth.M8FMSynthModABValues
          offset: 42
        mod_b1:
          enums:
          - m8.enums.fmsynth.M8FMSynthModABValues
          offset: 43
        mod_b2:
          enums:
          - m8.enums.fmsynth.M8FMSynthModABValues
          offset: 44
        mod_b3:
          enums:
          - m8.enums.fmsynth.M8FMSynthModABValues
          offset: 45
        mod_b4:
          enums:
          - m8.enums.fmsynth.M8FMSynthModABValues
          offset: 46
        pan:
          default: 128
          offset: 56
        ratio1:
          offset: 23
        ratio2:
          offset: 25
        ratio3:
          offset: 27
        ratio4:
          offset: 29
        ratio_fine1:
          offset: 24
        ratio_fine2:
          offset: 26
        ratio_fine3:
          offset: 28
        ratio_fine4:
          offset: 30
        res:
          offset: 53
        reverb:
          offset: 60
        shape1:
          enums:
          - m8.enums.fmsynth.M8FMSynthShapes
          offset: 19
        shape2:
          enums:
          - m8.enums.fmsynth.M8FMSynthShapes
          offset: 20
        shape3:
          enums:
          - m8.enums.fmsynth.M8FMSynthShapes
          offset: 21
        shape4:
          enums:
          - m8.enums.fmsynth.M8FMSynthShapes
          offset: 22
      type_id: 4
    HYPERSYNTH:
      params:
        amp:
          offset: 33
        chorus:
          offset: 37
        cutoff:
          default: 255
          offset: 31
        delay:
          offset: 38
        dry:
          default: 192
          offset: 36
        filter:
          enums:
          - m8.enums.M8FilterTypes
          offset: 30
        limit:
          enums:
          - m8.enums.M8LimitTypes
          offset: 34
        pan:
          default: 128
          offset: 35
        res:
          offset: 32
        reverb:
          offset: 39
      type_id: 5
    MACROSYNTH:
      params:
        amp:
          offset: 26
        chorus:
          offset: 30
        color:
          default: 128
          offset: 20
        cutoff:
          default: 255
          offset: 24
        degrade:
          offset: 21
        delay:
          offset: 31
        dry:
          default: 192
          offset: 29
        filter:
          enums:
          - m8.enums.M8FilterTypes
          offset: 23
        limit:
          enums:
          - m8.enums.M8LimitTypes
          offset: 27
        pan:
          default: 128
          offset: 28
        redux:
          offset: 22
        res:
          offset: 25
        reverb:
          offset: 32
        shape:
          enums:
          - m8.enums.macrosynth.M8MacroSynthShapes
          offset: 18
        timbre:
          default: 128
          offset: 19
      type_id: 1
    SAMPLER:
      params:
        amp:
          offset: 27
        chorus:
          offset: 31
        cutoff:
          default: 255
          offset: 25
        degrade:
          offset: 23
        delay:
          offset: 32
        dry:
          default: 192
          offset: 30
        filter:
          enums:
          - m8.enums.M8FilterTypes
          offset: 24
        length:
          default: 255
          offset: 22
        limit:
          enums:
          - m8.enums.M8LimitTypes
          offset: 28
        loop_start:
          offset: 21
        pan:
          default: 128
          offset: 29
        play_mode:
          enums:
          - m8.enums.sampler.M8SamplerPlayMode
          offset: 18
        res:
          offset: 26
        reverb:
          offset: 33
        slice:
          offset: 19
        start:
          offset: 20
      sample_path:
        default: ''
        offset: 87
        size: 128
        type: STRING
      type_id: 2
    WAVSYNTH:
      params:
        amp:
          offset: 26
        chorus:
          offset: 30
        cutoff:
          default: 255
          offset: 24
        delay:
          offset: 31
        dry:
          default: 192
          offset: 29
        filter:
          enums:
          - m8.enums.M8FilterTypes
          offset: 23
        limit:
          enums:
          - m8.enums.M8LimitTypes
          offset: 27
        mult:
          default: 128
          offset: 20
        pan:
          default: 128
          offset: 28
        res:
          offset: 25
        reverb:
          offset: 32
        scan:
          offset: 22
        shape:
          enums:
          - m8.enums.wavsynth.M8WavSynthShapes
          offset: 18
        size:
          default: 128
          offset: 19
        warp:
          offset: 21
      type_id: 0
metadata:
  block_size: 147
  fields:
    directory:
      default: /Songs/
      offset: 0
      size: 128
      type: STRING
    key:
      offset: 146
    name:
      default: HELLO
      offset: 134
      size: 12
      type: STRING
    quantize:
      offset: 133
    tempo:
      default: 120.0
      offset: 129
      size: 4
      type: FLOAT
    transpose:
      offset: 128
  offset: 14
midi_mapping:
  offset: 108030
modulators:
  block_size: 6
  constants:
    default_amount: 255
    empty_destination: 0
  count: 4
  default_config:
  - 0
  - 0
  - 3
  - 3
  fields:
    amount:
      default: 255
      offset: 1
    type_dest_byte:
      offset: 0
  type_id_map:
    0: m8.api.modulators.M8AHDEnvelope
    1: m8.api.modulators.M8ADSREnvelope
    2: m8.api.modulators.M8DrumEnvelope
    3: m8.api.modulators.M8LFO
    4: m8.api.modulators.M8TriggerEnvelope
    5: m8.api.modulators.M8TrackingEnvelope
  types:
    ADSR_ENVELOPE:
      fields:
        amount:
          default: 255
          offset: 1
        attack:
          offset: 2
        decay:
          default: 128
          offset: 3
        destination:
          enums:
            '0x00':
            - m8.enums.wavsynth.M8WavSynthModDestinations
            '0x01':
            - m8.enums.macrosynth.M8MacroSynthModDestinations
            '0x02':
            - m8.enums.sampler.M8SamplerModDestinations
            '0x04':
            - m8.enums.fmsynth.M8FMSynthModDestinations
            '0x05':
            - m8.enums.hypersynth.M8HyperSynthModDestinations
          nibble: 1
          offset: 0
        release:
          default: 128
          offset: 5
        sustain:
          default: 128
          offset: 4
      id: 1
    AHD_ENVELOPE:
      fields:
        amount:
          default: 255
          offset: 1
        attack:
          offset: 2
        decay:
          default: 128
          offset: 4
        destination:
          enums:
            '0x00':
            - m8.enums.wavsynth.M8WavSynthModDestinations
            '0x01':
            - m8.enums.macrosynth.M8MacroSynthModDestinations
            '0x02':
            - m8.enums.sampler.M8SamplerModDestinations
            '0x04':
            - m8.enums.fmsynth.M8FMSynthModDestinations
            '0x05':
            - m8.enums.hypersynth.M8HyperSynthModDestinations
          nibble: 1
          offset: 0
        hold:
          offset: 3
      id: 0
    DRUM_ENVELOPE:
      fields:
        amount:
          default: 255
          offset: 1
        body:
          default: 16
          offset: 3
        decay:
          default: 128
          offset: 4
        destination:
          enums:
            '0x00':
            - m8.enums.wavsynth.M8WavSynthModDestinations
            '0x01':
            - m8.enums.macrosynth.M8MacroSynthModDestinations
            '0x02':
            - m8.enums.sampler.M8SamplerModDestinations
            '0x04':
            - m8.enums.fmsynth.M8FMSynthModDestinations
            '0x05':
            - m8.enums.hypersynth.M8HyperSynthModDestinations
          nibble: 1
          offset: 0
        peak:
          offset: 2
      id: 2
    LFO:
      fields:
        amount:
          default: 255
          offset: 1
        destination:
          enums:
            '0x00':
            - m8.enums.wavsynth.M8WavSynthModDestinations
            '0x01':
            - m8.enums.macrosynth.M8MacroSynthModDestinations
            '0x02':
            - m8.enums.sampler.M8SamplerModDestinations
            '0x04':
            - m8.enums.fmsynth.M8FMSynthModDestinations
            '0x05':
            - m8.enums.hypersynth.M8HyperSynthModDestinations
          nibble: 1
          offset: 0
        frequency:
          default: 16
          offset: 4
        oscillator:
          offset: 2
        trigger:
          offset: 3
      id: 3
    TRACKING_ENVELOPE:
      fields:
        amount:
          default: 255
          offset: 1
        destination:
          enums:
            '0x00':
            - m8.enums.wavsynth.M8WavSynthModDestinations
            '0x01':
            - m8.enums.macrosynth.M8MacroSynthModDestinations
            '0x02':
            - m8.enums.sampler.M8SamplerModDestinations
            '0x04':
            - m8.enums.fmsynth.M8FMSynthModDestinations
            '0x05':
            - m8.enums.hypersynth.M8HyperSynthModDestinations
          nibble: 1
          offset: 0
        high_value:
          default: 127
          offset: 4
        low_value:
          offset: 3
        source:
          offset: 2
      id: 5
    TRIGGER_ENVELOPE:
      fields:
        amount:
          default: 255
          offset: 1
        attack:
          offset: 2
        decay:
          default: 64
          offset: 4
        destination:
          enums:
            '0x00':
            - m8.enums.wavsynth.M8WavSynthModDestinations
            '0x01':
            - m8.enums.macrosynth.M8MacroSynthModDestinations
            '0x02':
            - m8.enums.sampler.M8SamplerModDestinations
            '0x04':
            - m8.enums.fmsynth.M8FMSynthModDestinations
            '0x05':
            - m8.enums.hypersynth.M8HyperSynthModDestinations
          nibble: 1
          offset: 0
        hold:
          offset: 3
        source:
          offset: 5
      id: 4
phrases:
  constants:
    base_data_size: 3
    empty_instrument: 255
    empty_note: 255
    empty_velocity: 255
  count: 255
  fields:
    fx:
      offset: 3
      size: 6
    instrument:
      default: 255
      offset: 2
    note:
      default: 255
      enums:
      - m8.enums.M8Notes
      offset: 0
    velocity:
      default: 255
      offset: 1
  offset: 2798
  step_count: 16
  step_size: 9
scale:
  offset: 109182
song:
  col_count: 8
  constants:
    empty_chain: 255
  offset: 750
  row_count: 255
table:
  offset: 47678
version:
  offset: 10
