version:
  offset: 0x0A
  
metadata:
  offset: 0x0E
  block_size: 147
  fields:
    directory: {offset: 0, size: 128, type: "STRING", default: "/Songs/"}
    transpose: {offset: 128}
    tempo: {offset: 129, size: 4, type: "FLOAT", default: 120.0}
    quantize: {offset: 133}
    name: {offset: 134, size: 12, type: "STRING", default: "HELLO"}
    key: {offset: 146}
  
groove:
  offset: 0xEE
  
song:
  offset: 0x2EE
  row_count: 255
  col_count: 8
  constants:
    empty_chain: 0xFF
  
phrases:
  offset: 0xAEE
  count: 255
  step_count: 16
  step_size: 9
  constants:
    base_data_size: 3
    empty_note: 0xFF
    empty_velocity: 0xFF
    empty_instrument: 0xFF
  fields:
    note: {offset: 0, default: 0xFF}
    velocity: {offset: 1, default: 0xFF}
    instrument: {offset: 2, default: 0xFF}
    fx: {offset: 3, size: 6, type: "UINT8", default: 0x00}
  
chains:
  offset: 0x9A5E
  count: 128
  step_count: 16
  step_size: 2
  constants:
    empty_phrase: 0xFF
    default_transpose: 0x00
  fields:
    phrase: {offset: 0, default: 0xFF}
    transpose: {offset: 1, default: 0x00}
  
table:
  offset: 0xBA3E
  
fx:
  block_size: 2
  block_count: 3
  constants:
    default_value: 0x00
    empty_key: 0xFF
  fields:
    key: {offset: 0, default: 0xFF}
    value: {offset: 1, default: 0x00}
  
instruments:
  offset: 0x13A3E
  count: 128
  block_size: 215
  modulators_offset: 63
  
  # Common parameter offsets for all instrument types
  common_offsets:
    type: 0
    name: 1
    name_length: 12
    transpose_eq: 13
    table_tick: 14
    volume: 15
    pitch: 16
    finetune: 17
    
  # Common parameter defaults for all instrument types
  common_defaults:
    name: " "
    transpose: 0x4
    eq: 0x1
    table_tick: 0x01
    volume: 0x0
    pitch: 0x0
    finetune: 0x80
  
  # Parameter types enum
  param_types:
    UINT8: 1
    STRING: 2
  
  WAVSYNTH:
    type_id: 0x00
    params:
      shape: {offset: 18, default: 0x00, enums: ["m8.enums.wavsynth.M8WavSynthShapes"]}
      size: {offset: 19, default: 0x80}
      mult: {offset: 20, default: 0x80}
      warp: {offset: 21, default: 0x00}
      scan: {offset: 22, default: 0x00}
      filter: {offset: 23, default: 0x00, enums: ["m8.enums.M8FilterTypes"]}
      cutoff: {offset: 24, default: 0xFF}
      res: {offset: 25, default: 0x00}
      amp: {offset: 26, default: 0x00}
      limit: {offset: 27, default: 0x00, enums: ["m8.enums.M8LimitTypes"]}
      pan: {offset: 28, default: 0x80}
      dry: {offset: 29, default: 0xC0}
      chorus: {offset: 30, default: 0x00}
      delay: {offset: 31, default: 0x00}
      reverb: {offset: 32, default: 0x00}
    
  MACROSYNTH:
    type_id: 0x01
    params:
      shape: {offset: 18, default: 0x00, enums: ["m8.enums.macrosynth.M8MacroSynthShapes"]}
      timbre: {offset: 19, default: 0x80}
      color: {offset: 20, default: 0x80}
      degrade: {offset: 21, default: 0x00}
      redux: {offset: 22, default: 0x00}
      filter: {offset: 23, default: 0x00, enums: ["m8.enums.M8FilterTypes"]}
      cutoff: {offset: 24, default: 0xFF}
      res: {offset: 25, default: 0x00}
      amp: {offset: 26, default: 0x00}
      limit: {offset: 27, default: 0x00, enums: ["m8.enums.M8LimitTypes"]}
      pan: {offset: 28, default: 0x80}
      dry: {offset: 29, default: 0xC0}
      chorus: {offset: 30, default: 0x00}
      delay: {offset: 31, default: 0x00}
      reverb: {offset: 32, default: 0x00}
  
  SAMPLER:
    type_id: 0x02
    params:
      play_mode: {offset: 18, default: 0x00, enums: ["m8.enums.sampler.M8SamplerPlayMode"]}
      slice: {offset: 19, default: 0x00}
      start: {offset: 20, default: 0x00}
      loop_start: {offset: 21, default: 0x00}
      length: {offset: 22, default: 0xFF}
      degrade: {offset: 23, default: 0x00}
      filter: {offset: 24, default: 0x00, enums: ["m8.enums.M8FilterTypes"]}
      cutoff: {offset: 25, default: 0xFF}
      res: {offset: 26, default: 0x00}
      amp: {offset: 27, default: 0x00}
      limit: {offset: 28, default: 0x00, enums: ["m8.enums.M8LimitTypes"]}
      pan: {offset: 29, default: 0x80}
      dry: {offset: 30, default: 0xC0}
      chorus: {offset: 31, default: 0x00}
      delay: {offset: 32, default: 0x00}
      reverb: {offset: 33, default: 0x00}
    sample_path: {offset: 87, size: 128, type: "STRING", default: ""}
    
effect_settings:
  offset: 0x1A5C1
  
midi_mapping:
  offset: 0x1A5FE
  
scale:
  offset: 0x1AA7E
  
eq:
  offset: 0x1AD5E

modulators:
  block_size: 6
  count: 4
  default_config: [0x00, 0x00, 0x03, 0x03]  # 2 AHD envelopes, 2 LFOs
  
  constants:
    empty_destination: 0x00
    default_amount: 0xFF
  
  fields:
    type_dest_byte: {offset: 0, default: 0x00}
    amount: {offset: 1, default: 0xFF}
  
  type_id_map:
    0x00: "m8.api.modulators.M8AHDEnvelope"
    0x01: "m8.api.modulators.M8ADSREnvelope"
    0x02: "m8.api.modulators.M8DrumEnvelope"
    0x03: "m8.api.modulators.M8LFO"
    0x04: "m8.api.modulators.M8TriggerEnvelope"
    0x05: "m8.api.modulators.M8TrackingEnvelope"
  
  types:
    AHD_ENVELOPE: 
      id: 0x00
      fields:
        destination: {
          offset: 0, 
          nibble: 1, 
          type: "UINT8", 
          default: 0x00, 
          enums: {
            "0x00": ["m8.enums.wavsynth.M8WavSynthModDestinations"],
            "0x01": ["m8.enums.macrosynth.M8MacroSynthModDestinations"],
            "0x02": ["m8.enums.sampler.M8SamplerModDestinations"]
          }
        }
        amount: {offset: 1, default: 0xFF}
        attack: {offset: 2, default: 0x00}
        hold: {offset: 3, default: 0x00}
        decay: {offset: 4, default: 0x80}
    
    ADSR_ENVELOPE:
      id: 0x01
      fields:
        destination: {
          offset: 0, 
          nibble: 1, 
          type: "UINT8", 
          default: 0x00, 
          enums: {
            "0x00": ["m8.enums.wavsynth.M8WavSynthModDestinations"],
            "0x01": ["m8.enums.macrosynth.M8MacroSynthModDestinations"],
            "0x02": ["m8.enums.sampler.M8SamplerModDestinations"]
          }
        }
        amount: {offset: 1, default: 0xFF}
        attack: {offset: 2, default: 0x00}
        decay: {offset: 3, default: 0x80}
        sustain: {offset: 4, default: 0x80}
        release: {offset: 5, default: 0x80}
    
    DRUM_ENVELOPE:
      id: 0x02
      fields:
        destination: {
          offset: 0, 
          nibble: 1, 
          type: "UINT8", 
          default: 0x00, 
          enums: {
            "0x00": ["m8.enums.wavsynth.M8WavSynthModDestinations"],
            "0x01": ["m8.enums.macrosynth.M8MacroSynthModDestinations"],
            "0x02": ["m8.enums.sampler.M8SamplerModDestinations"]
          }
        }
        amount: {offset: 1, default: 0xFF}
        peak: {offset: 2, default: 0x00}
        body: {offset: 3, default: 0x10}
        decay: {offset: 4, default: 0x80}
    
    LFO:
      id: 0x03
      fields:
        destination: {
          offset: 0, 
          nibble: 1, 
          type: "UINT8", 
          default: 0x00, 
          enums: {
            "0x00": ["m8.enums.wavsynth.M8WavSynthModDestinations"],
            "0x01": ["m8.enums.macrosynth.M8MacroSynthModDestinations"],
            "0x02": ["m8.enums.sampler.M8SamplerModDestinations"]
          }
        }
        amount: {offset: 1, default: 0xFF}
        oscillator: {offset: 2, default: 0x00}
        trigger: {offset: 3, default: 0x00}
        frequency: {offset: 4, default: 0x10}
    
    TRIGGER_ENVELOPE:
      id: 0x04
      fields:
        destination: {
          offset: 0, 
          nibble: 1, 
          type: "UINT8", 
          default: 0x00, 
          enums: {
            "0x00": ["m8.enums.wavsynth.M8WavSynthModDestinations"],
            "0x01": ["m8.enums.macrosynth.M8MacroSynthModDestinations"],
            "0x02": ["m8.enums.sampler.M8SamplerModDestinations"]
          }
        }
        amount: {offset: 1, default: 0xFF}
        attack: {offset: 2, default: 0x00}
        hold: {offset: 3, default: 0x00}
        decay: {offset: 4, default: 0x40}
        source: {offset: 5, default: 0x00}
    
    TRACKING_ENVELOPE:
      id: 0x05
      fields:
        destination: {
          offset: 0, 
          nibble: 1, 
          type: "UINT8", 
          default: 0x00, 
          enums: {
            "0x00": ["m8.enums.wavsynth.M8WavSynthModDestinations"],
            "0x01": ["m8.enums.macrosynth.M8MacroSynthModDestinations"],
            "0x02": ["m8.enums.sampler.M8SamplerModDestinations"]
          }
        }
        amount: {offset: 1, default: 0xFF}
        source: {offset: 2, default: 0x00}
        low_value: {offset: 3, default: 0x00}
        high_value: {offset: 4, default: 0x7F}